dist: trusty
sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer
language: scala
sbt_args: -J-Dproject.version=travis-SNAPSHOT
scala:
  - 2.11.11
cache:
  directories:
    - $HOME/.ivy2
    - $HOME/.sbt
